service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

functions:
  getProductsList:
    handler: handlers.getProductsList
    events:
      - httpApi:
          method: get
          path: /products
  getProductsById:
    handler: handlers.getProductsById
    events:
      - httpApi:
          method: get
          path: /products/{param}
